---
- name: install and start the vsftpd service
  hosts: all
  tasks: 
    - name: install vsftpd
      yum:
        name: vsftpd
        state: latest
    - name: start the vsftpd service
      service:
        name: vsftpd
        state: started
        enabled: yes
...
